# Generated by Django 6.0.1 on 2026-01-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
